### ISSUE TITLE
Outdated postman collection

### ISSUE THREAD

**Issue by JakuSw** [mollie/postman-collection#4]
Hi Mollie Team,

It looks like postman collection lacks `cancelUrl` for creating payment, would be great to update it 😄

**Comment by fjbender** [comment]
We are on it :)

**Comment by jwarne-mollie** [comment]
Will be fixed as part of [this PR](https://github.com/mollie/postman-collection/pull/6)

**Comment by jwarne-mollie** [comment]
Will be fixed as part of [this PR](https://github.com/mollie/postman-collection/pull/6)
